# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- pr

variables:
 key1: $(KEY2)

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script: python -m pip install --upgrade pytest-azure-devops
- script: python -m pip install --upgrade mkdocs
- script: pytest test/test_cal.py
# - script: mkdir -p ~/.ssh 
# - script: echo "$key1" > ~/.ssh/id_rsa 
# - script: chmod 600 ~/.ssh/id_rsa 
# - script: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
- script: git config --global user.email "bartwoesik1@gmail.com"
- script: git config --global user.name "bartvanwoesik"
- script: git config --global credential.helper store 
- script: git remote set-url origin https://bartvanwoesik:$(key1)@github.com/bartvanwoesik/mkdocs_tutorial.git
- script: git fetch --all
- script: git config --global credential.helper 'store --file ~/.git-credentials'
- script: echo "https://bartvanwoesik:$(key1)@github.com" > ~/.git-credentials
- script: mkdocs gh-deploy --force