# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- pr

variables:
 key1: $(KEY2)

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Check pytests!
  displayName: 'Run pytest before merging'

- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script: python -m pip install --upgrade pytest-azure-devops
- script: python -m pip install --upgrade mkdocs
- script: pytest test/test_cal.py
