# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
 key1: $(KEY1)

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script: python -m pip install --upgrade pytest-azure-devops
- script: python -m pip install --upgrade mkdocs
- script: pytest test/test_cal.py
- script: 
    # Set up SSH authentication using the secret key
    mkdir -p ~/.ssh
    echo "$key1" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    
- script: git remote set-url origin git@github.com:bartvanwoesik/mkdocs_tutorial.git
- script: mkdocs gh-deploy